name: Build package-test

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  expand-matrix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Expand matrix
        id: expand
        uses: ./.github/actions/expand-matrix
        with:
          matrix: |
            el9: x86_64
            debian12: x86_64
            ubuntu24: x86_64

    outputs:
      matrix: ${{ steps.expand.outputs.matrix }}

  build:
    needs: expand-matrix
    uses: lbetz/ci-workflows/.github/workflows/build.yml@main
    with:
      ci_workflows_ref: "main"
      matrix: ${{ needs.expand-matrix.outputs.matrix }}
